name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish -c Release -o mvctest
    - name: Zip Folder
      run: zip -r App.zip mvctest/*
    - name: Move App.zip to windows-lb/App folder
      run: mv App.zip windows-lb/App/
    - name: Execute terraform code
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 0.12.25
    - run: terraform init windows-lb
    - id: plan
      run: terraform plan windows-lb -no-color
    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
        
